<a href="https://colab.research.google.com/github/ZaietsMykytaFIT/DTEU-Machine-Learning-2025-Zaiets/blob/main/Zaiets_Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Лабораторна робота 1: Вступ до машинного навчання. Елементи лінійної алгебри.
Варіант 3

In [69]:
import numpy as np
np.__version__

'2.0.2'

Завдання 1: Створіть одновимірний масив (вектор) з парними числами від 2 до 20 та виведіть його значення

In [70]:
np.array(list(range(2, 21, 2)), dtype = int)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Завдання 2: Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його випадковими дійсними числами від 0 до 1 та виведіть його значення.

In [71]:
np.round(np.random.rand(3, 3), 2)

array([[0.54, 0.22, 0.35],
       [0.16, 0.65, 0.6 ],
       [0.31, 0.01, 0.52]])

Завдання 3: Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від 1 до 20 та виведіть його значення

In [72]:
np.random.randint(1, 21, (3, 3))

array([[ 2, 10,  7],
       [ 1, 20,  7],
       [ 7,  3, 11]])

Завдання 4: Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть мінімальний елемент.

In [73]:
array = np.random.rand(4, 4)
array, array.min()

(array([[0.38541452, 0.59036063, 0.38997084, 0.20158145],
        [0.78573637, 0.42478835, 0.41497579, 0.28686039],
        [0.32401275, 0.95632608, 0.09944045, 0.60689552],
        [0.47878694, 0.08413886, 0.20814651, 0.77485847]]),
 np.float64(0.08413886466913545))

Завдання 5: Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від -20 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.

In [74]:
arr1, arr2 = np.random.randint(-20, 21, 6), np.random.randint(-20, 21, 6)
arr1, arr2, arr1 + arr2, arr1 - arr2, arr1 * arr2
#  orig x2,      +,           -,           *.

(array([ 19, -11,  -2,  -4,  18,   7]),
 array([19, -4, 12, 10,  2,  9]),
 array([ 38, -15,  10,   6,  20,  16]),
 array([  0,  -7, -14, -14,  16,  -2]),
 array([361,  44, -24, -40,  36,  63]))

Завдання 6: Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 3 до 30 та знайдіть їх добуток.

In [85]:
arr1, arr2 = np.random.randint(3, 31, (3, 3)), np.random.randint(3, 31, (3, 3))
arr1*arr2

array([[306, 187, 234],
       [494, 588, 336],
       [ 70,  64, 364]])

Завдання 7: Створіть дві матриці розміром 4x2 та 2x5, заповніть їх випадковими цілими числами в діапазоні від 1 до 7 та перемножте їх між собою

In [76]:
arr1, arr2 = np.random.randint(1, 7, (4, 2)), np.random.randint(1, 7, (2, 5))
arr1, arr2, np.dot(arr1, arr2)

(array([[6, 5],
        [1, 3],
        [6, 1],
        [5, 1]]),
 array([[1, 4, 5, 5, 5],
        [2, 4, 4, 6, 4]]),
 array([[16, 44, 50, 60, 50],
        [ 7, 16, 17, 23, 17],
        [ 8, 28, 34, 36, 34],
        [ 7, 24, 29, 31, 29]]))

Завдання 8: Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 8 та знайдіть її обернену матрицю

In [89]:
arr = np.random.randint(1, 8, (2, 2))
arr_i = np.linalg.inv(arr)
arr, arr_i

(array([[4, 1],
        [3, 1]]),
 array([[ 1., -1.],
        [-3.,  4.]]))

Завдання 9: Створіть матрицю розміром 2x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [78]:
arr = np.random.rand(2, 3)
arr, arr.T

(array([[0.92823271, 0.58622705, 0.21783023],
        [0.02293492, 0.94112042, 0.11583533]]),
 array([[0.92823271, 0.02293492],
        [0.58622705, 0.94112042],
        [0.21783023, 0.11583533]]))

Завдання 10: Створіть матрицю розміром 3x4 та вектор розміром 4 x1, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть добуток матриці на вектор

In [79]:
arr, vector = np.random.randint(1, 11, (3, 4)), np.random.randint(1, 11, (4, 1))
result = np.dot(arr, vector)
arr, vector, result

(array([[ 5, 10, 10,  5],
        [ 8,  7,  7,  7],
        [ 7,  8,  2,  3]]),
 array([[ 7],
        [ 4],
        [ 9],
        [10]]),
 array([[215],
        [217],
        [129]]))

Завдання 11: Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [80]:
arr, vector = np.random.rand(2, 3), np.random.randint(1, 11, (3, 1))
result = np.dot(arr, vector)
arr, vector, result

(array([[0.61524581, 0.41600399, 0.36844008],
        [0.78320618, 0.83313431, 0.82031673]]),
 array([[3],
        [7],
        [7]]),
 array([[ 7.33684596],
        [13.92377585]]))

Завдання 12: Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню суму.

In [81]:
arr1, arr2 = np.random.randint(1, 11, (4, 4)), np.random.randint(1, 11, (4, 4))
arr1 + arr2

array([[12, 10,  7,  4],
       [ 7, 13,  8,  2],
       [14,  5,  8, 15],
       [10, 11, 13, 16]])

Завдання 13: Створіть дві матриці розміром 4x4, заповніть їх випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть їх добуток

In [82]:
arr1, arr2 = np.random.uniform(-1, 1, (4, 4)), np.random.uniform(-1, 1, (4, 4))
np.dot(arr1, arr2)

array([[ 0.326998  ,  1.10944736, -0.35179978, -1.2203833 ],
       [-0.11134722, -0.20639556,  0.43543062,  0.49891803],
       [ 0.55442771,  0.65186221,  0.03633012, -0.80052022],
       [ 1.12925468,  0.21014341,  0.19723676, -0.62722618]])

Завдання 14: Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть суму елементів матриці

In [83]:
np.sum(np.random.uniform(-1, 1, (3, 3)))

np.float64(0.8294585283622213)

Завдання 15: Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [84]:
np.sum(np.random.uniform(-0.5, 0.5, (5, 5)), axis = 1)

array([0.08022205, 0.93103929, 0.0383561 , 0.30106613, 0.28767618])

Висновок: Я згадав як ініціалізувати масиви та виконувати елементарні дії над ними.